gallery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('sticker.urls')),
]

sticker/urls.py
from django.conf.urls import url

from . import views

app_name = 'sticker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('about/', views.about, name='about'),
    url(r'^sticker/(?P<md5>[0-9a-z]+)/$', views.singleDetailView.as_view(), name='single'),
    url(r'^category/(?P<cate>.*?)/$', views.categoryListView.as_view(), name='category'),
]

sticker/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sticker:category', kwargs={'cate': self.name})

class Sticker(models.Model):
    title  = models.CharField(max_length=70)
    author = models.CharField(max_length=70)

    content = models.TextField()
    md5 = models.CharField(max_length=32)

    created_time = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)

    # 贴吧名字
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title\

    def get_absolute_url(self):
        return reverse('sticker:single', kwargs={'md5': self.md5})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

sticker/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Sticker, Category
import markdown

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

class categoryListView(ListView):
    model = Category
    template_name = 'category.html'
    context_object_name = 'category'
    paginate_by = 2

    def get_queryset(self):
        cate = super(categoryListView, self).get_queryset().filter(name=self.kwargs.get('cate')).values()
        cateid = cate[0]['id']        
        return singleDetailView().get_queryset().filter(category=cateid)


    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data

class singleDetailView(DetailView):
    model = Sticker
    template_name = 'single.html'
    context_object_name = 'sticker'

    def get_object(self, queryset=None):
        sticker = get_object_or_404(Sticker, md5=self.kwargs['md5'])
        sticker.increase_views()
        sticker.content = markdown.markdown(sticker.content,
                                    extensions=[
                                        'markdown.extensions.extra',
                                        'markdown.extensions.codehilite',
                                        'markdown.extensions.toc',
                                    ])
        return sticker

templates/about.html
{% extends 'base.html' %}

{% block main %}
    <p>本项目是用来练手<a href='https://www.djangoproject.com/'>Django</a>的项目，由一个博客模板改造而成。你可以把它当作一个博客，也可以当成在线文档阅读器，其实大同小异。现存的几篇文档是从网上抓取而来，仅供测试使用。</p>
    <p>&nbsp;</p>
    <p>本项目的相关文档会发布在我的博客上，如下：</p>
    <ul>
        <li><a href='https://journal.ethanshub.com/post/category/gong-cheng-shi/-pythonkai-fa-djangokuang-jia-he-wang-zhan'>使用Django框架开发一个网站</a></li>
    </ul>
    <p>代码在Github上：<a href='https://github.com/wfgydbu/A-Django-Content-Site'>A-Django-Content-Site</a>例子。</p>
    <p>&nbsp;</p>
    <p>祝好</p>
    <p><a href='https://journal.ethanshub.com/'>Ethan</a></p>
{% endblock main %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Home</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   
    <!-- Font-Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    
    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="theme-styles">

    <!--[if lt IE 9]>      
        <script src="js/respond.js"></script>
    <![endif]-->
    
</head>
<body>
    <header>
        {% include "common/navigation.html" %}
    </header>

    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-main">
                    {% block main %}
                    {% endblock main %}
                </div>
                <aside class="col-md-4 blog-aside">
                    
                    <div class="aside-widget">
                        {% include "common/feature.html" %}
                    </div>

                    <div class="aside-widget">
                        {% include "common/tags.html" %}
                    </div>
                </aside>
            </div>
        </div>
    </div>

    <footer>
        {% include "common/footer.html" %}
    </footer>
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/modernizr.js' %}"></script>

</body>
</html>

templates/category.html
{% extends 'base.html' %}

{% block main %}
<ul>
    {% for single in category %}
        <li>
            <a href='{{ single.get_absolute_url }}'>{{ single }}</a>
        </li>
    {% empty %}
    暂无内容！
    {% endfor %}
</ul>

{% if is_paginated %}
<div class="pagination">
    {% if first %}
        <a href="?page=1">1</a>
    {% endif %}
    {% if left %}
        {% if left_has_more %}
            <span>...</span>
        {% endif %}
        {% for i in left %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
    {% endif %}
    <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
    {% if right %}
        {% for i in right %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if right_has_more %}
            <span>...</span>
        {% endif %}
    {% endif %}
    {% if last %}
        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
    {% endif %}
</div>
{% endif %}
{% endblock main %}

templates/common/feature.html
{% load staticfiles %}
{% load customTags %}
{% load customFilter %}

<header>
    <h3>热门帖子</h3>
</header>
<div class="body">
    <ul class="clean-list">
        {% get_recent_stickers as recent_stickers_list %}
        {% for sticker in recent_stickers_list %}
        <li>
            <a href="{{ sticker.get_absolute_url }}">{{ sticker.title|title_tunc }}</a>
        </li>
        {% empty %}
        暂无内容！
        {% endfor %}
    </ul>
</div>

templates/common/footer.html
{% load staticfiles %}
<div class="widewrapper footer">
    <div class="container">
        <div class="row">
            <div class="footer-widget">
                <h4> <i class="fa fa-user"></i>关于本项目</h4>
                <p>本项目是用来练手<a href='https://www.djangoproject.com/'>Django</a>的项目，由一个博客模板改造而成。你可以把它当作一个博客，也可以当成在线文档阅读器，其实大同小异。现存的几篇文档是从网上抓取而来，仅供测试使用。</p>
            </div>
        </div>
    </div>
</div>
<div class="widewrapper copyright">
        Copyright 2015 . 模板来源 <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> ，内容经过修改。</a>
</div>

templates/common/navigation.html
{% load staticfiles %}
{% load customTags %}

<div class="widewrapper masthead">
    <div class="container">
        <a href="{% url 'sticker:index' %}" id="logo">
            <img src="{% static 'img/logo.png' %}" alt="clean Blog">
        </a>

        <div id="mobile-nav-toggle" class="pull-right">
            <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                <i class="fa fa-bars"></i>
            </a>
        </div>

        <nav class="pull-right clean-nav">
            <div class="collapse navbar-collapse">
                <ul class="nav nav-pills navbar-nav">
                  
                    <li>
                        <a href="{% url 'sticker:index' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'sticker:about' %}">About</a>
                    </li>                        
                </ul>
            </div>
        </nav>        

    </div>
</div>

<div class="widewrapper subheader">
    <div class="container">
        <div class="clean-breadcrumb">
            {% parser_full_url request.get_full_path request.path as res %}
            {{ res }}
        </div>
        <!--
        <div class="clean-searchbox">
            <form action="#" method="get" accept-charset="utf-8">
                <input class="searchfield" id="searchbox" type="text" placeholder="Search">
                <button class="searchbutton" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </form>
        </div>-->
    </div>
</div>

templates/common/tags.html
{% load staticfiles %}
{% load customTags %}

<header>
    <h3>其他类别</h3>
</header>
<div class="body clearfix">
    <ul class="tags">
        {% get_categories as categories_list %}
        {% for category in categories_list %}
        <li>
            <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
        </li>
        {% empty %}
        暂无内容！
        {% endfor %}
    </ul>
</div>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load customTags %}

{% block main %}
<div class="row">
    {% get_all_categories as categories_list %}
    {% for category in categories_list %}
    <div class="col-md-6 col-sm-6">
        <article class=" blog-teaser">
            <header>
                <p>
                <a href="{{ category.get_absolute_url }}">
                <img src="{% static 'images/' %}{{ category.name }}/{{ category.name }}.jpg" alt=""></p>
                <h3><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></h3>
            </header>
            <hr>
        </article>
    </div>
    {% empty %}
    暂无内容！
    {% endfor %}

</div>
{% endblock main %}

templates/single.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
<article class="blog-post">
    <div class="body">
        <h2>{{ sticker.title }}</h2>
        <div class="meta">
            <i class="fa fa-user"></i>{{ sticker.author }}<i class="fa fa-calendar"></i>{{ sticker.created_time }}<i class="fa fa-comments"></i>{{ sticker.views }} 阅读
        </div>
        <pre>{{ sticker.content|safe }}</pre>
    </div>
</article>
{% endblock main %}